### ISSUE TITLE
Servers not listed

### ISSUE THREAD

**Issue by tlewis17** [illiteratealliterator/manymine#1]
This is an amazing concept, but neither of my servers are actually listed.

Here is the log files from the manymine container. It sees the 2 servers being registered.  Here are the logs and the section of YAML. This is running on Docker on Ubuntu 18.x

```
MM_LISTEN_PORT=19132,
Listening for pings at 0.0.0.0:19132,
Server added: /Games_minecraft_creative1.1.7py70wgltljl0kymyeo9xicif (6a1f062712b98772ffb93906599a5a4156bd224939004a62edd6f8b0ae6336a8),
Server added: /Games_minecraft_survival1.1.v8gsd3l0cgh4gkdckkt5nellu (c255f3e2821c1f3562b3f19f979170973f0f3635792062219896302c74d0d835),
Server /Games_minecraft_creative1.1.7py70wgltljl0kymyeo9xicif has no mapping for internal port 19132,
Server /Games_minecraft_survival1.1.v8gsd3l0cgh4gkdckkt5nellu has no mapping for internal port 19132,
Server removed: /Games_minecraft_survival1.1.v8gsd3l0cgh4gkdckkt5nellu (c255f3e2821c1f3562b3f19f979170973f0f3635792062219896302c74d0d835),
Server removed: /Games_minecraft_creative1.1.7py70wgltljl0kymyeo9xicif (6a1f062712b98772ffb93906599a5a4156bd224939004a62edd6f8b0ae6336a8),
Server added: /Games_minecraft_survival1.1.mn3mpfwp161ymmsvqu6ks4frj (5bcb00a8131073622f51292e3c93c000f265af4604546edd100113fb014ed0d2),
Server /Games_minecraft_survival1.1.mn3mpfwp161ymmsvqu6ks4frj has no mapping for internal port 19132,
Server added: /Games_minecraft_creative1.1.ne1b7wxjxjta8b6wpag1h214m (e3b6bbd1a5d3b81ef6d5d9a3480a36b1b274963a76c6e0cab1d8992f5709a26b),
Server /Games_minecraft_creative1.1.ne1b7wxjxjta8b6wpag1h214m has no mapping for internal port 19132,
```

``` yaml
  manymine:
    image: illiteratealliterator/manymine
    ports:
      - '19132:19132/udp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  minecraft_survival1:
      image: itzg/minecraft-bedrock-server
      environment:
        - EULA=TRUE
        - SERVER_NAME=Survival1
        - GAMEMODE=survival
        - DIFFICULTY=easy
        - LEVEL_TYPE=default
        - ALLOW_CHEATS=false
        - LEVEL_SEED=1935762385
        - SERVER_PORT=60601
      ports:
        - 60601:60601/udp
      labels:
        - manymine.enable=true
      dns: 192.168.0.1
      volumes:
        - mc_survival1:/data
      stdin_open: true
      tty: true
  minecraft_creative1:
      image: itzg/minecraft-bedrock-server
      environment:
        - EULA=TRUE
        - SERVER_NAME=Creative1
        - GAMEMODE=creative
        - DIFFICULTY=peaceful
        - LEVEL_TYPE=default
        - ALLOW_CHEATS=false
        - LEVEL_SEED=1935762385
        - SERVER_PORT=60602
      ports:
        - 60602:60602/udp
      labels:
        - manymine.enable=true
      dns: 192.168.0.1
      volumes:
        - mc_creative1:/data
      stdin_open: true
      tty: true
```
