### ISSUE TITLE
Exception on connecting: Error: Read error for name : 67 is not in the mappings value

### ISSUE THREAD

**Issue by ndtreviv** [illiteratealliterator/manymine#6]
I'm using this in conjunction with https://github.com/cubeworx/mcbe-server which says it's compatible. However, when I `docker-compose up` the various bedrock servers come up, but then restart almost immediately (possibly because they're updating the version of bedrock server, which they do automatically on startup). At which point they go from Initial to No Response in the manymine logs.
When I try to connect with a Nintendo Switch (via Bedrock Connect - why do Nintendo make it so hard?!) I get an exception in the manymine logs:

```
Listening for pings at 0.0.0.0:19132
Server added: /mc-survival (324f5a98b075416b0e89fd4b51aba0c399b302f05e6ec0133043af3f523c0809)
Server /mc-survival is running on internal port 60602 and external port 60602
/mc-survival (172.19.0.3:60602) changed state from [Initial] to [No Response]
Server added: /mc-creative (05f2c3e189c343341e6fa25d1039300369228cf323d6acfce2b697fcdf3e0a29)
Server /mc-creative is running on internal port 60601 and external port 60601
/mc-creative (172.19.0.4:60601) changed state from [Initial] to [No Response]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Read error for name : 67 is not in the mappings value
    at ProtoDef.readMapper (/usr/src/app/node_modules/protodef/src/datatypes/utils.js:30:34)
    at ProtoDef.read (/usr/src/app/node_modules/protodef/src/protodef.js:110:29)
    at /usr/src/app/node_modules/protodef/src/datatypes/structures.js:45:32
    at tryCatch (/usr/src/app/node_modules/protodef/src/utils.js:50:16)
    at tryDoc (/usr/src/app/node_modules/protodef/src/utils.js:54:10)
    at /usr/src/app/node_modules/protodef/src/datatypes/structures.js:44:5
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (/usr/src/app/node_modules/protodef/src/datatypes/structures.js:43:12)
    at ProtoDef.read (/usr/src/app/node_modules/protodef/src/protodef.js:36:25)
    at ProtoDef.read (/usr/src/app/node_modules/protodef/src/protodef.js:110:29)
Emitted 'error' event on Parser instance at:
    at errorOrDestroy (/usr/src/app/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
    at onwriteError (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:424:5)
    at onwrite (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:450:11)
    at WritableState.onwrite (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:160:5)
    at Parser.afterTransform (/usr/src/app/node_modules/readable-stream/lib/_stream_transform.js:89:3)
    at Parser._transform (/usr/src/app/node_modules/protodef/src/serializer.js:49:18)
    at Parser.Transform._read (/usr/src/app/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Parser.Transform._write (/usr/src/app/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:398:5) {
  field: 'name',
  buffer: Buffer(87) [Uint8Array] [
     67,  80,  69,  59,  67, 114, 101, 97, 116, 105, 118, 101,
     59,  52,  55,  53,  59,  49,  46, 49,  56,  46,  50,  59,
     48,  59,  49,  48,  59,  49,  50, 55,  52,  57,  50,  51,
     54,  55,  52,  51,  52,  54,  51, 51,  48,  51,  50,  50,
     54,  59,  66, 101, 100, 114, 111, 99, 107,  45,  76, 101,
    118, 101, 108,  59,  67, 114, 101, 97, 116, 105, 118, 101,
     59,  49,  59,  54,  48,  54,  48, 49,  59,  54,  53,  53,
     51,  53,  59
  ]
```

The  manymine container crashed at this point, so I `docker-compose up` again and I got this in the logs (see below), although this time the bedrock servers didn't restart, so I'm not sure why they moved from Connected to No Response? The logs on the bedrock servers all look good:

```
mc-manymine    | /mc-creative (172.19.0.4:60601) changed state from [Initial] to [Connected]
mc-manymine    | /mc-survival (172.19.0.3:60602) changed state from [Initial] to [No Response]
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
mc-manymine    | Received unexpected packet on listen port: open_connection_request_1
```

Even after bringing it up again, the Switch still couldn't connect to any worlds.

**Comment by ndtreviv** [comment]
This is my docker-compose file:

```
version: "3.7"
services:
  manymine:
    image: illiteratealliterator/manymine
    container_name: mc-manymine
    ports:
      - '19132:19132/udp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  minecraft-a:
    image: cubeworx/mcbe-server
    container_name: mc-creative
    environment:
      - EULA=TRUE
      - SERVER_NAME=Creative
      - GAME_MODE=creative
      - ALLOW_CHEATS=true
      - DIFFICULTY=normal
      - OPERATORS=ndtreviv
      - SERVER_PORT=60601
    volumes:
      - /Users/nathan/mc-creative-data:/mcbe/data
    ports:
      - '60601:60601/udp'
    labels:
      - manymine.enable=true

  minecraft-b:
    image: cubeworx/mcbe-server
    container_name: mc-survival
    environment:
      - EULA=TRUE
      - SERVER_NAME=Survival
      - GAME_MODE=survival
      - ALLOW_CHEATS=true
      - DIFFICULTY=normal
      - OPERATORS=ndtreviv
    volumes:
      - /Users/nathan/mc-survival-data:/mcbe/data
    ports:
      - '60602:60602/udp'
    labels:
      - manymine.enable=true
```
